name: npm-build-publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish package on PyPI 📦
        run: pypa/gh-action-pypi-publish@v1.5.1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
