name: npm-build-publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish package on PyPI 📦
        uses: pypa/gh-action-pypi-publish@v1.5.1
        env:
          password: ${{ secrets.GITHUB_TOKEN }}
          repository_url: https://pypi.pkg.github.com/sudip-mondal-2002
